"""
GridPulse AI — ORM Schemas (SQLAlchemy Table Definitions)
Defines the physical database tables that back the time-series telemetry store.

Tables
------
• telemetry_readings   — raw + ML-annotated meter readings (Features 1–6 + sustainability)
• forecast_snapshots   — per-meter 24-hour load forecasts (Feature 5)
• users                — registered operator accounts for JWT authentication (Feature 7)

Design decisions:
  • UUID primary key   — globally unique, no auto-increment contention at scale.
  • server_default=now() — timestamp set by DB, immune to client clock skew.
  • Composite index (meter_id, timestamp DESC) — covers the most common query:
      "give me the last N readings for meter X".
  • Separate index on timestamp alone — covers fleet-wide range queries.
  • CHECK constraints mirror Pydantic validation so bad data can't sneak in
    via direct SQL inserts.
  • edge_flagged / edge_confidence (Feature 6) — nullable with server-side
      DEFAULT FALSE so all pre-Feature-6 rows remain valid without backfill.
  • carbon_intensity_gco2_kwh — nullable; NULL for rows ingested before the
      sustainability feature was deployed (fully backward-compatible).
"""
import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Float,
    Index,
    Integer,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models in this project."""
    pass


class TelemetryReading(Base):
    """
    One row = one instantaneous measurement from a smart meter.

    Columns
    -------
    id                       UUID PK generated by the DB (gen_random_uuid).
    meter_id                 Opaque string identifier supplied by the meter firmware.
    timestamp                UTC wall-clock time the reading was captured, set server-side.
    voltage                  RMS voltage in Volts. Typical residential: 220 V – 240 V.
    current                  RMS current in Amperes.
    power_factor             Dimensionless ratio [0.0, 1.0].  ≥ 0.8 for healthy grid loads.

    -- ML Analytics columns (populated asynchronously by the analytics service) --
    is_anomalous             True when the reading was flagged by anomaly detection.
    anomaly_type             Short label: 'voltage_sag', 'line_tapping', 'ml_outlier', etc.
    anomaly_confidence       Detection confidence [0.0 – 1.0]; NULL for normal readings.
    predicted_load_24h       Forecasted aggregate load 24 h from this reading (Watts).

    -- Economic Impact columns (Feature 3 — Financial Engine) ---------------
    revenue_loss_inr         Estimated revenue loss for this anomaly event (Indian Rupees).
    outage_risk_score        Composite transformer/substation stress score [0 – 100].

    -- Sustainability columns ------------------------------------------------
    carbon_intensity_gco2_kwh  Grid carbon intensity in gCO₂/kWh [150–800].
                               Lower during solar peak hours (09–16h UTC local),
                               higher at night (18–06h) to simulate coal reliance.
                               NULL for legacy rows ingested before this feature.
    """

    __tablename__ = "telemetry_readings"
    __table_args__ = (
        # ── Composite index: most queries filter by meter then slice by time ──
        Index(
            "ix_telemetry_meter_timestamp",
            "meter_id",
            text("timestamp DESC"),  # DESC so the latest rows are cheapest
        ),
        # ── Range-scan index for fleet-wide time-window queries ───────────────
        Index("ix_telemetry_timestamp", text("timestamp DESC")),
        # ── Domain constraints (defence-in-depth beyond Pydantic) ─────────────
        CheckConstraint("voltage  >= 0",           name="ck_voltage_non_negative"),
        CheckConstraint("current  >= 0",           name="ck_current_non_negative"),
        CheckConstraint(
            "power_factor >= 0.0 AND power_factor <= 1.0",
            name="ck_power_factor_range",
        ),
    )

    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="Globally unique reading identifier",
    )

    # Meter identifier
    meter_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="Opaque identifier of the originating smart meter",
    )

    # Timestamp — authoritative server time, timezone-aware UTC
    timestamp: Mapped[str] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        comment="UTC moment the reading was ingested",
    )

    # Electrical metrics
    voltage: Mapped[float] = mapped_column(
        Float(precision=6),
        nullable=False,
        comment="RMS voltage (Volts)",
    )

    current: Mapped[float] = mapped_column(
        Float(precision=6),
        nullable=False,
        comment="RMS current (Amperes)",
    )

    power_factor: Mapped[float] = mapped_column(
        Float(precision=6),
        nullable=False,
        comment="Power factor [0.0 – 1.0]",
    )

    # ── ML Analytics columns (written by the background analytics service) ────
    # All nullable so rows are valid immediately after ingest, before analytics runs.

    is_anomalous: Mapped[bool | None] = mapped_column(
        Boolean,
        nullable=True,
        default=False,
        server_default=text("false"),
        comment="True when flagged as anomalous by the ML pipeline",
    )

    anomaly_type: Mapped[str | None] = mapped_column(
        String(64),
        nullable=True,
        comment="Short label: voltage_sag | voltage_swell | low_power_factor | line_tapping | ml_outlier",
    )

    anomaly_confidence: Mapped[float | None] = mapped_column(
        Float(precision=6),
        nullable=True,
        comment="Anomaly detection confidence [0.0 – 1.0]; NULL for normal readings",
    )

    predicted_load_24h: Mapped[float | None] = mapped_column(
        Float(precision=6),
        nullable=True,
        comment="Forecasted aggregate load 24 hours from this reading (Watts)",
    )

    # ── Economic Impact columns (Feature 3 — Financial Engine) ───────────────

    revenue_loss_inr: Mapped[float | None] = mapped_column(
        Float(precision=8),
        nullable=True,
        comment="Estimated revenue loss for this anomaly event (Indian Rupees)",
    )

    outage_risk_score: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Composite transformer/substation stress score [0 – 100]; NULL for normal readings",
    )

    # ── Feature 6: Edge AI pre-screening metadata ─────────────────────────────
    # Both columns are nullable with a server-side default of FALSE / NULL so
    # all existing rows (written before Feature 6) are valid without backfill.
    # A partial index on edge_flagged=true accelerates the priority-analytics
    # query that skips baseline Isolation Forest for pre-screened anomalies.

    edge_flagged: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("FALSE"),
        index=True,
        comment="True when the edge node pre-screener flagged this reading (Feature 6)",
    )

    edge_confidence: Mapped[float | None] = mapped_column(
        Float(precision=6),
        nullable=True,
        comment="Edge pre-screening confidence [0.0–1.0]; NULL for non-flagged readings",
    )

    # ── Sustainability column ─────────────────────────────────────────────────
    # Nullable — NULL for all rows ingested before the sustainability feature
    # was deployed.  No backfill required; backward-compatible.

    carbon_intensity_gco2_kwh: Mapped[float | None] = mapped_column(
        Float(precision=6),
        nullable=True,
        comment=(
            "Grid carbon intensity in gCO\u2082/kWh [150\u2013800]. "
            "Lower during solar peak hours (09\u201316h), higher at night (18\u201306h)."
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover
        anomaly_flag  = " ⚠ANOMALY" if self.is_anomalous else ""
        edge_flag     = " ⚡EDGE"    if self.edge_flagged  else ""
        carbon_str    = (
            f" 🌿{self.carbon_intensity_gco2_kwh:.0f}gCO₂/kWh"
            if self.carbon_intensity_gco2_kwh is not None else ""
        )
        return (
            f"<TelemetryReading meter={self.meter_id!r} "
            f"voltage={self.voltage:.1f}V pf={self.power_factor:.3f}"
            f"{anomaly_flag}{edge_flag}{carbon_str}>"
        )


# ── Feature 5: Forecast Snapshots ─────────────────────────────────────────────

class ForecastSnapshot(Base):
    """
    One row per meter per background forecast sweep.

    Written by ForecastingService.run_forecast_sweep() and read exclusively
    by GET /api/v1/grid/forecast — the heavy ML computation is fully decoupled
    from the API read path.

    Columns
    -------
    id                   UUID PK.
    meter_id             Opaque meter identifier.
    generated_at         UTC timestamp when this forecast was computed.
    forecast_horizon     generated_at + 24 h — the end of the forecast window.
    predicted_peak_w     Maximum predicted load across the 24-step trajectory (W).
    predicted_avg_w      Mean predicted load across the 24-step trajectory (W).
    outage_risk_score    Composite risk score [0–100] derived from peak vs capacity.
    risk_zone            Qualitative label: 'low' | 'medium' | 'high' | 'critical'.
    capacity_threshold_w Substation capacity limit used for risk scoring (W).
    model_name           Identifier of the forecaster that produced this snapshot.
    """

    __tablename__ = "forecast_snapshots"
    __table_args__ = (
        # Fast lookup: latest forecast for each meter
        Index(
            "ix_forecast_meter_generated",
            "meter_id",
            text("generated_at DESC"),
        ),
        # Fleet-wide scan: all forecasts within a time window
        Index("ix_forecast_generated", text("generated_at DESC")),
        # Partial index: high-priority risk zone queries
        Index(
            "ix_forecast_high_risk",
            "meter_id",
            "outage_risk_score",
            postgresql_where=text("risk_zone IN ('high', 'critical')"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="Globally unique forecast identifier",
    )

    meter_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="Opaque identifier of the meter being forecast",
    )

    generated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        comment="UTC moment this forecast snapshot was computed",
    )

    forecast_horizon: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        comment="UTC end-of-window for this forecast (generated_at + 24 h)",
    )

    predicted_peak_w: Mapped[float] = mapped_column(
        Float(precision=8),
        nullable=False,
        comment="Maximum predicted load in the 24-hour window (Watts)",
    )

    predicted_avg_w: Mapped[float] = mapped_column(
        Float(precision=8),
        nullable=False,
        comment="Mean predicted load in the 24-hour window (Watts)",
    )

    outage_risk_score: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Composite outage risk score [0–100]",
    )

    risk_zone: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        comment="Qualitative risk band: low | medium | high | critical",
    )

    capacity_threshold_w: Mapped[float] = mapped_column(
        Float(precision=8),
        nullable=False,
        comment="Substation capacity limit used for risk scoring (Watts)",
    )

    model_name: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        comment="Name of the forecaster model that produced this snapshot",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<ForecastSnapshot meter={self.meter_id!r} "
            f"risk={self.risk_zone} score={self.outage_risk_score} "
            f"peak={self.predicted_peak_w:.1f}W>"
        )


# ── Feature 7: Operator User Accounts (JWT Authentication) ────────────────────

class User(Base):
    """
    One row = one registered grid operator account.

    Passwords are stored as bcrypt hashes only — the plain-text password
    is never persisted anywhere in the system.  Authentication is handled
    by core.security.verify_password().

    Columns
    -------
    id               UUID PK generated by the DB.
    username         Unique display name used as the JWT 'sub' claim.
    hashed_password  bcrypt hash of the user's password.
    created_at       UTC registration timestamp, set server-side.
    """

    __tablename__ = "users"
    __table_args__ = (
        UniqueConstraint("username", name="uq_users_username"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="Globally unique user identifier",
    )

    username: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
        comment="Unique operator username; used as JWT sub claim",
    )

    hashed_password: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        comment="bcrypt hash of the user's password — never store plaintext",
    )

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
        comment="UTC moment the account was created",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User username={self.username!r} id={self.id}>"
