"""Mako script template for Alembic — do not delete."""
"""initial_telemetry_table

Revision ID: 993a2a1551dd
Revises: 
Create Date: 2026-06-24 11:51:34.800753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '993a2a1551dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_readings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Globally unique reading identifier'),
    sa.Column('meter_id', sa.String(length=64), nullable=False, comment='Opaque identifier of the originating smart meter'),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False, comment='UTC moment the reading was ingested'),
    sa.Column('voltage', sa.Float(precision=6), nullable=False, comment='RMS voltage (Volts)'),
    sa.Column('current', sa.Float(precision=6), nullable=False, comment='RMS current (Amperes)'),
    sa.Column('power_factor', sa.Float(precision=6), nullable=False, comment='Power factor [0.0 – 1.0]'),
    sa.CheckConstraint('current  >= 0', name='ck_current_non_negative'),
    sa.CheckConstraint('power_factor >= 0.0 AND power_factor <= 1.0', name='ck_power_factor_range'),
    sa.CheckConstraint('voltage  >= 0', name='ck_voltage_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_meter_timestamp', 'telemetry_readings', ['meter_id', sa.text('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_telemetry_readings_meter_id'), 'telemetry_readings', ['meter_id'], unique=False)
    op.create_index('ix_telemetry_timestamp', 'telemetry_readings', [sa.text('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_timestamp', table_name='telemetry_readings')
    op.drop_index(op.f('ix_telemetry_readings_meter_id'), table_name='telemetry_readings')
    op.drop_index('ix_telemetry_meter_timestamp', table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    # ### end Alembic commands ###
